### ISSUE TITLE
Vorschlag für Thema

### ISSUE THREAD

**Issue by rwa96** [ob-algdatii-ss18/leistungsnachweis-ride-distributor#1]
Verbesserung meiner [Abgabe](https://github.com/rwa96/HashCode18) bei der diesjährigen [Google-HashCode online quallification](https://hashcode.withgoogle.com/2018/tasks/hashcode2018_qualification_task.pdf).

**Comment by obcode** [comment]
👍

**Comment by obcode** [comment]
Label bitte noch entsprechend setzen.
